/// <reference types="chrome" />

export const PLAY_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>`;
export const PAUSE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><rect x="6" y="4" width="4" height="16"/><rect x="14" y="4" width="4" height="16"/></svg>`;

export const dom = {
  get dropZone() { return document.getElementById('drop-zone') as HTMLElement; },
  get dragOverlay() { return document.getElementById('drag-overlay') as HTMLElement; },
  get loadingIndicator() { return document.getElementById('loading-indicator') as HTMLElement; },
  get loadingText() { return document.getElementById('loading-text') as HTMLElement; },
  get readerModeView() { return document.getElementById('reader-mode-view') as HTMLElement; },
  get readerContent() { return document.getElementById('reader-content') as HTMLElement; },
  get readerBookTitle() { return document.getElementById('reader-book-title') as HTMLElement; },
  get readerPageInfo() { return document.getElementById('reader-page-info') as HTMLElement; },
  get readerWordCount() { return document.getElementById('reader-word-count') as HTMLElement; },
  get pdfViewer() { return document.getElementById('pdf-viewer') as HTMLElement; },
  get pagesContainer() { return document.getElementById('pages-container') as HTMLElement; },
  get fileInput() { return document.getElementById('file-input') as HTMLInputElement; },
  get dropFileInput() { return document.getElementById('drop-file-input') as HTMLInputElement; },
  get docInfo() { return document.getElementById('doc-info') as HTMLElement; },
  get docTitle() { return document.getElementById('doc-title') as HTMLElement; },
  get navControls() { return document.getElementById('nav-controls') as HTMLElement; },
  get sidebarToggleBtn() { return document.getElementById('sidebar-toggle-btn') as HTMLButtonElement; },
  get readerSidebar() { return document.getElementById('reader-sidebar') as HTMLElement; },
  get sidebarCloseBtn() { return document.getElementById('sidebar-close-btn') as HTMLButtonElement; },
  get sidebarSearchInput() { return document.getElementById('sidebar-search-input') as HTMLInputElement; },
  get sidebarPageList() { return document.getElementById('sidebar-page-list') as HTMLElement; },
  get modeReaderBtn() { return document.getElementById('mode-reader-btn') as HTMLButtonElement; },
  get modePdfBtn() { return document.getElementById('mode-pdf-btn') as HTMLButtonElement; },
  get pdfCanvasControls() { return document.getElementById('pdf-canvas-controls') as HTMLElement; },
  get fontDecreaseBtn() { return document.getElementById('font-decrease-btn') as HTMLButtonElement; },
  get fontIncreaseBtn() { return document.getElementById('font-increase-btn') as HTMLButtonElement; },
  get fontSizePreview() { return document.getElementById('font-size-preview') as HTMLElement; },
  get fontFamilySelect() { return document.getElementById('font-family-select') as HTMLSelectElement; },
  get pageNumInput() { return document.getElementById('page-num-input') as HTMLInputElement; },
  get pageCountSpan() { return document.getElementById('page-count') as HTMLElement; },
  get prevPageBtn() { return document.getElementById('prev-page-btn') as HTMLButtonElement; },
  get nextPageBtn() { return document.getElementById('next-page-btn') as HTMLButtonElement; },
  get zoomOutBtn() { return document.getElementById('zoom-out-btn') as HTMLButtonElement; },
  get zoomInBtn() { return document.getElementById('zoom-in-btn') as HTMLButtonElement; },
  get zoomLevelSpan() { return document.getElementById('zoom-level') as HTMLElement; },
  get fitWidthBtn() { return document.getElementById('fit-width-btn') as HTMLButtonElement; },
  get voiceSelect() { return document.getElementById('voice-select') as HTMLSelectElement; },
  get rateSlider() { return document.getElementById('rate-slider') as HTMLInputElement; },
  get speedLabel() { return document.getElementById('speed-label') as HTMLElement; },
  get ttsPlayBtn() { return document.getElementById('tts-play-btn') as HTMLButtonElement; },
  get ttsPlayIcon() { return document.getElementById('tts-play-icon') as HTMLElement; },
  get ttsStopBtn() { return document.getElementById('tts-stop-btn') as HTMLButtonElement; },
  get ttsPrevBtn() { return document.getElementById('tts-prev-btn') as HTMLButtonElement; },
  get ttsNextBtn() { return document.getElementById('tts-next-btn') as HTMLButtonElement; },
  get autoScrollBtn() { return document.getElementById('auto-scroll-btn') as HTMLButtonElement; },
  get exportDocBtn() { return document.getElementById('export-doc-btn') as HTMLButtonElement; },
  get undoEditBtn() { return document.getElementById('undo-edit-btn') as HTMLButtonElement; },
  get libraryMenuBtn() { return document.getElementById('library-menu-btn') as HTMLButtonElement; },
  get libraryMenu() { return document.getElementById('library-menu') as HTMLElement; },
  get appearanceMenuBtn() { return document.getElementById('appearance-menu-btn') as HTMLButtonElement; },
  get appearanceMenu() { return document.getElementById('appearance-menu') as HTMLElement; },
  get recentFilesList() { return document.getElementById('recent-files-list') as HTMLElement; },
  get clearRecentsBtn() { return document.getElementById('clear-recents-btn') as HTMLButtonElement; },
  get dropRecentSection() { return document.getElementById('drop-recent-section') as HTMLElement; },
  get dropRecentList() { return document.getElementById('drop-recent-list') as HTMLElement; },
  get aiSettingsBtn() { return document.getElementById('ai-settings-btn') as HTMLButtonElement; },
  get aiModal() { return document.getElementById('ai-modal') as HTMLElement; },
  get aiModalClose() { return document.getElementById('ai-modal-close') as HTMLButtonElement; },
  get aiModalCancel() { return document.getElementById('ai-modal-cancel') as HTMLButtonElement; },
  get aiModalSave() { return document.getElementById('ai-modal-save') as HTMLButtonElement; },
  get geminiApiKeyInput() { return document.getElementById('gemini-api-key-input') as HTMLInputElement; },
  get geminiModelInput() { return document.getElementById('gemini-model-input') as HTMLInputElement; },
  get toggleKeyVisibility() { return document.getElementById('toggle-key-visibility') as HTMLButtonElement; }
};

export const hoverPlayButton = document.createElement('button');
hoverPlayButton.id = 'edge-tts-hover-play';
hoverPlayButton.innerHTML = PLAY_SVG;
document.body.appendChild(hoverPlayButton);
